import { StyleSheet } from 'react-native'
import { AppTheme } from '@/src/shared/theme/colors'
import { typography } from '@/src/shared/theme/typography'

export function createStyles({ colors, shadows }: AppTheme) {
  return StyleSheet.create({
    content: {
      paddingHorizontal: 0,
      paddingTop: 0,
    },
    inner: {
      padding: 18,
    },
    titleRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 22,
      marginTop: 22,
    },
    title: {
      color: colors.text,
      fontFamily: typography.familyBold,
      fontSize: typography.size.screenTitle,
      fontWeight: typography.weight.bold,
    },
    addButton: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 24,
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    addButtonSpacer: {
      height: 48,
      width: 48,
    },
    stateBlock: {
      alignItems: 'center',
      gap: 10,
      paddingVertical: 28,
    },
    stateText: {
      color: colors.textMuted,
      fontFamily: typography.familyBold,
      fontSize: typography.size.bodySmall,
      fontWeight: typography.weight.medium,
    },
    errorBlock: {
      alignItems: 'center',
      backgroundColor: colors.dangerSoft,
      gap: 12,
      padding: 16,
    },
    errorText: {
      color: colors.danger,
      fontFamily: typography.familyBold,
      fontSize: typography.size.bodySmall,
      fontWeight: typography.weight.semibold,
      textAlign: 'center',
    },
    retryButton: {
      alignItems: 'center',
      backgroundColor: colors.danger,
      borderRadius: 8,
      flexDirection: 'row',
      gap: 8,
      minHeight: 48,
      paddingHorizontal: 14,
    },
    retryText: {
      color: colors.white,
      fontFamily: typography.familyBold,
      fontSize: typography.size.label,
      fontWeight: typography.weight.bold,
    },
    emptyCard: {
      alignItems: 'center',
      gap: 8,
      paddingVertical: 28,
    },
    emptyTitle: {
      color: colors.text,
      fontFamily: typography.familyBold,
      fontSize: typography.size.titleSmall,
      fontWeight: typography.weight.bold,
    },
    emptyText: {
      color: colors.textMuted,
      fontFamily: typography.family,
      fontSize: typography.size.bodySmall,
      lineHeight: typography.lineHeight.bodySmall,
      textAlign: 'center',
    },
    list: {
      gap: 12,
    },
    tabRow: {
      backgroundColor: colors.surfaceMuted,
      borderColor: colors.surfaceVariant,
      borderRadius: 10,
      borderWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      gap: 4,
      marginBottom: 18,
      padding: 4,
    },
    tabButton: {
      alignItems: 'center',
      borderRadius: 8,
      flex: 1,
      justifyContent: 'center',
      minHeight: 48,
      paddingHorizontal: 12,
    },
    tabButtonActive: {
      backgroundColor: colors.surface,
    },
    tabText: {
      color: colors.textMuted,
      fontFamily: typography.familyBold,
      fontSize: typography.size.label,
      fontWeight: typography.weight.semibold,
      textAlign: 'center',
    },
    tabTextActive: {
      color: colors.primary,
    },
    peopleBlock: {
      gap: 14,
    },
    groupCard: {
      alignItems: 'center',
      borderRadius: 12,
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 82,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    left: {
      alignItems: 'center',
      flex: 1,
      flexDirection: 'row',
      gap: 14,
      minWidth: 0,
    },
    groupText: {
      flex: 1,
      minWidth: 0,
    },
    groupName: {
      color: colors.text,
      fontFamily: typography.familyBold,
      fontSize: typography.size.titleSmall,
      fontWeight: typography.weight.semibold,
    },
    groupMembers: {
      color: colors.textMuted,
      fontFamily: typography.family,
      fontSize: typography.size.bodySmall,
      marginTop: 4,
    },
    right: {
      alignItems: 'center',
      flexDirection: 'row',
    },
    modalOverlay: {
      alignItems: 'center',
      backgroundColor: colors.overlay,
      flex: 1,
      justifyContent: 'center',
      padding: 18,
    },
    modalCard: {
      borderRadius: 14,
      gap: 18,
      width: '100%',
    },
    detailsCard: {
      borderRadius: 14,
      gap: 16,
      maxHeight: '82%',
      width: '100%',
    },
    modalHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    detailsHeaderText: {
      flex: 1,
      paddingRight: 12,
    },
    detailsSubtitle: {
      color: colors.textMuted,
      fontFamily: typography.family,
      fontSize: typography.size.bodySmall,
      marginTop: 4,
    },
    modalTitle: {
      color: colors.text,
      fontFamily: typography.familyBold,
      fontSize: typography.size.title,
      fontWeight: typography.weight.bold,
    },
    closeButton: {
      alignItems: 'center',
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    fieldGroup: {
      gap: 8,
    },
    label: {
      color: colors.text,
      fontFamily: typography.familyBold,
      fontSize: typography.size.body,
      fontWeight: typography.weight.semibold,
    },
    input: {
      borderColor: colors.outline,
      borderRadius: 12,
      borderWidth: 1,
      color: colors.text,
      fontFamily: typography.family,
      fontSize: typography.size.bodyLarge,
      height: 54,
      paddingHorizontal: 16,
    },
    createButton: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 24,
      flexDirection: 'row',
      gap: 8,
      height: 52,
      justifyContent: 'center',
    },
    disabledButton: {
      opacity: 0.72,
    },
    createText: {
      color: colors.white,
      fontFamily: typography.familyBold,
      fontSize: typography.size.body,
      fontWeight: typography.weight.bold,
    },
    memberErrorBlock: {
      backgroundColor: colors.dangerSoft,
      borderRadius: 12,
      padding: 12,
    },
    memberList: {
      gap: 10,
      paddingBottom: 4,
    },
    modalScrollArea: {
      flexShrink: 1,
    },
    memberRow: {
      alignItems: 'center',
      borderColor: colors.surfaceVariant,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: 'row',
      minHeight: 72,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    memberTitleRow: {
      alignItems: 'center',
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    roleTag: {
      backgroundColor: colors.primarySoft,
      borderRadius: 6,
      color: colors.primary,
      fontFamily: typography.familyBold,
      fontSize: typography.size.caption,
      fontWeight: typography.weight.semibold,
      overflow: 'hidden',
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    addMemberBlock: {
      borderTopColor: colors.surfaceVariant,
      borderTopWidth: StyleSheet.hairlineWidth,
      gap: 14,
      paddingTop: 16,
    },
    searchState: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
    },
    searchResults: {
      borderColor: colors.surfaceVariant,
      borderRadius: 12,
      borderWidth: 1,
      overflow: 'hidden',
    },
    searchResultRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
      minHeight: 68,
      padding: 12,
    },
    addMemberIconButton: {
      alignItems: 'center',
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    copyIconButton: {
      alignItems: 'center',
      borderColor: colors.primarySoft,
      borderRadius: 24,
      borderWidth: StyleSheet.hairlineWidth,
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    pendingList: {
      backgroundColor: colors.surfaceMuted,
      borderRadius: 12,
      gap: 10,
      padding: 12,
    },
    pendingTitle: {
      color: colors.textMuted,
      fontFamily: typography.familyBold,
      fontSize: typography.size.label,
      fontWeight: typography.weight.semibold,
    },
    pendingRow: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.surfaceVariant,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 12,
      minHeight: 68,
      padding: 10,
    },
    removePendingButton: {
      alignItems: 'center',
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    expenseListBlock: {
      flexShrink: 1,
      gap: 12,
    },
    expenseList: {
      gap: 10,
      paddingBottom: 4,
    },
    expenseRow: {
      alignItems: 'center',
      borderColor: colors.surfaceVariant,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
      minHeight: 76,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    expenseIcon: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 22,
      height: 44,
      justifyContent: 'center',
      width: 44,
    },
    expenseAmountBlock: {
      alignItems: 'flex-end',
      flexDirection: 'row',
      flexShrink: 0,
      gap: 4,
    },
    expenseAmount: {
      color: colors.text,
      fontFamily: typography.familyBold,
      fontSize: typography.size.body,
      fontWeight: typography.weight.bold,
    },
    expenseDetails: {
      flexShrink: 1,
      gap: 14,
    },
    backToListButton: {
      alignItems: 'center',
      alignSelf: 'flex-start',
      flexDirection: 'row',
      minHeight: 48,
      paddingRight: 12,
    },
    backToListText: {
      color: colors.primary,
      fontFamily: typography.familyBold,
      fontSize: typography.size.body,
      fontWeight: typography.weight.semibold,
    },
    expenseSummary: {
      backgroundColor: colors.surfaceMuted,
      borderRadius: 12,
      gap: 12,
      padding: 14,
    },
    expenseDetailTitle: {
      color: colors.text,
      fontFamily: typography.familyBold,
      fontSize: typography.size.title,
      fontWeight: typography.weight.bold,
    },
    expenseDetailAmount: {
      color: colors.primary,
      fontFamily: typography.familyBold,
      fontSize: typography.size.screenTitle,
      fontWeight: typography.weight.bold,
    },
    expenseMetaGrid: {
      flexDirection: 'row',
      gap: 12,
    },
    expenseMetaItem: {
      flex: 1,
      gap: 3,
    },
    expenseMetaLabel: {
      color: colors.textMuted,
      fontFamily: typography.familyBold,
      fontSize: typography.size.caption,
      fontWeight: typography.weight.semibold,
      textTransform: 'uppercase',
    },
    expenseMetaValue: {
      color: colors.text,
      fontFamily: typography.family,
      fontSize: typography.size.bodySmall,
    },
    shareList: {
      gap: 10,
      paddingBottom: 4,
    },
    shareRow: {
      alignItems: 'center',
      borderColor: colors.surfaceVariant,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 72,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    shareAmount: {
      color: colors.text,
      flexShrink: 0,
      fontFamily: typography.familyBold,
      fontSize: typography.size.body,
      fontWeight: typography.weight.bold,
      paddingLeft: 12,
    },
    loadMoreButton: {
      alignItems: 'center',
      borderColor: colors.primarySoft,
      borderRadius: 24,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'center',
      minHeight: 48,
    },
    loadMoreText: {
      color: colors.primary,
      fontFamily: typography.familyBold,
      fontSize: typography.size.body,
      fontWeight: typography.weight.bold,
    },
  })
}
