import { StyleSheet } from 'react-native'
import { colors, shadows } from '@/src/shared/theme/colors'

export const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  content: {
    paddingBottom: 160,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  balanceGrid: {
    flexDirection: 'row',
    gap: 18,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 24,
  },
  balanceCard: {
    flex: 1,
    borderRadius: 14,
    gap: 18,
    minHeight: 108,
    paddingHorizontal: 18,
    paddingVertical: 20,
  },
  balanceLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  balanceLabel: {
    color: colors.textMuted,
    fontSize: 16,
    fontWeight: '600',
  },
  balanceAmount: {
    fontSize: 31,
    fontWeight: '800',
  },
  stateBlock: {
    alignItems: 'center',
    gap: 10,
    paddingBottom: 10,
    paddingTop: 4,
  },
  stateText: {
    color: colors.textMuted,
    fontSize: 16,
    fontWeight: '600',
  },
  errorBlock: {
    alignItems: 'center',
    backgroundColor: colors.dangerSoft,
    gap: 12,
    marginHorizontal: 18,
    marginTop: 8,
    padding: 16,
  },
  errorText: {
    color: colors.danger,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  retryButton: {
    alignItems: 'center',
    backgroundColor: colors.danger,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  retryText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 12,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 27,
    fontWeight: '700',
  },
  viewAll: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  viewAllText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  list: {
    gap: 10,
    paddingHorizontal: 18,
    paddingTop: 14,
  },
  balanceItem: {
    backgroundColor: colors.surface,
    borderColor: colors.surfaceVariant,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 84,
    overflow: 'hidden',
    ...shadows.card,
  },
  statusBar: {
    width: 5,
  },
  itemContent: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  itemLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 14,
  },
  itemText: {
    flex: 1,
  },
  itemName: {
    color: colors.text,
    fontSize: 21,
    fontWeight: '700',
  },
  titleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  itemTitle: {
    color: colors.textMuted,
    fontSize: 16,
  },
  tag: {
    backgroundColor: colors.surfaceVariant,
    borderRadius: 6,
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  itemRight: {
    alignItems: 'flex-end',
    minWidth: 104,
  },
  itemAmount: {
    fontSize: 21,
    fontWeight: '800',
  },
  itemLabel: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '600',
    marginTop: 4,
  },
  emptyCard: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 24,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 21,
    maxWidth: 280,
    textAlign: 'center',
  },
  fab: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 22,
    bottom: 24,
    height: 74,
    justifyContent: 'center',
    position: 'absolute',
    right: 28,
    width: 74,
    ...shadows.floating,
  },
})
