import { StyleSheet } from 'react-native'
import { colors, shadows } from '@/src/shared/theme/colors'
import { typography } from '@/src/shared/theme/typography'

export const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  content: {
    paddingBottom: 160,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  balanceGrid: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 24,
  },
  balanceCard: {
    flex: 1,
    borderRadius: 12,
    gap: 14,
    minHeight: 100,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  balanceLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  balanceLabel: {
    color: colors.textMuted,
    fontFamily: typography.family,
    fontSize: typography.size.bodySmall,
    fontWeight: typography.weight.medium,
  },
  balanceAmount: {
    fontFamily: typography.family,
    fontSize: typography.size.screenTitle,
    fontWeight: typography.weight.bold,
  },
  stateBlock: {
    alignItems: 'center',
    gap: 10,
    paddingBottom: 10,
    paddingTop: 4,
  },
  stateText: {
    color: colors.textMuted,
    fontFamily: typography.family,
    fontSize: typography.size.bodySmall,
    fontWeight: typography.weight.medium,
  },
  errorBlock: {
    alignItems: 'center',
    backgroundColor: colors.dangerSoft,
    gap: 12,
    marginHorizontal: 18,
    marginTop: 8,
    padding: 16,
  },
  errorText: {
    color: colors.danger,
    fontFamily: typography.family,
    fontSize: typography.size.label,
    fontWeight: typography.weight.semibold,
    textAlign: 'center',
  },
  retryButton: {
    alignItems: 'center',
    backgroundColor: colors.danger,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  retryText: {
    color: colors.white,
    fontFamily: typography.family,
    fontSize: typography.size.label,
    fontWeight: typography.weight.bold,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 12,
  },
  sectionTitle: {
    color: colors.text,
    fontFamily: typography.family,
    fontSize: typography.size.section,
    fontWeight: typography.weight.semibold,
  },
  viewAll: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  viewAllText: {
    color: colors.primary,
    fontFamily: typography.family,
    fontSize: typography.size.label,
    fontWeight: typography.weight.semibold,
  },
  list: {
    gap: 10,
    paddingHorizontal: 18,
    paddingTop: 14,
  },
  balanceItem: {
    backgroundColor: colors.surface,
    borderColor: colors.surfaceVariant,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 84,
    overflow: 'hidden',
    ...shadows.card,
  },
  statusBar: {
    width: 5,
  },
  itemShell: {
    flex: 1,
  },
  itemContent: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  itemLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 14,
  },
  itemText: {
    flex: 1,
  },
  itemName: {
    color: colors.text,
    fontFamily: typography.family,
    fontSize: typography.size.titleSmall,
    fontWeight: typography.weight.semibold,
  },
  titleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  itemTitle: {
    color: colors.textMuted,
    fontFamily: typography.family,
    fontSize: typography.size.label,
  },
  tag: {
    backgroundColor: colors.surfaceVariant,
    borderRadius: 6,
    color: colors.textMuted,
    fontFamily: typography.family,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.semibold,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  itemRight: {
    alignItems: 'flex-end',
    minWidth: 104,
  },
  itemAmount: {
    fontFamily: typography.family,
    fontSize: typography.size.titleSmall,
    fontWeight: typography.weight.bold,
  },
  itemLabel: {
    color: colors.textMuted,
    fontFamily: typography.family,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.medium,
    marginTop: 4,
  },
  emptyCard: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 24,
  },
  emptyTitle: {
    color: colors.text,
    fontFamily: typography.family,
    fontSize: typography.size.bodyLarge,
    fontWeight: typography.weight.bold,
  },
  emptyText: {
    color: colors.textMuted,
    fontFamily: typography.family,
    fontSize: typography.size.label,
    lineHeight: typography.lineHeight.bodySmall,
    maxWidth: 280,
    textAlign: 'center',
  },
  fab: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 20,
    bottom: 24,
    height: 64,
    justifyContent: 'center',
    position: 'absolute',
    right: 28,
    width: 64,
    ...shadows.floating,
  },
  reviewActions: {
    borderTopColor: colors.surfaceVariant,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
    paddingBottom: 12,
    paddingHorizontal: 14,
  },
  reviewButton: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 36,
    minWidth: 92,
    paddingHorizontal: 12,
  },
  acceptButton: {
    backgroundColor: colors.primary,
  },
  rejectButton: {
    backgroundColor: colors.surface,
    borderColor: colors.danger,
    borderWidth: StyleSheet.hairlineWidth,
  },
  actionPressed: {
    opacity: 0.65,
  },
  reviewButtonText: {
    fontFamily: typography.family,
    fontSize: typography.size.label,
    fontWeight: typography.weight.semibold,
  },
  acceptButtonText: {
    color: colors.white,
  },
  rejectButtonText: {
    color: colors.danger,
  },
})
