export const typography = {
  familyBrand: 'Caveat_700Bold',
  family: 'PTSans_400Regular',
  familyRegular: 'PTSans_400Regular',
  familyBold: 'PTSans_700Bold',
  size: {
    caption: 12,
    label: 14,
    bodySmall: 15,
    body: 16,
    bodyLarge: 17,
    titleSmall: 18,
    title: 22,
    section: 24,
    screenTitle: 30,
    hero: 40,
    amount: 64,
  },
  lineHeight: {
    bodySmall: 21,
    body: 22,
    bodyLarge: 24,
    title: 28,
  },
  weight: {
    regular: '400' as const,
    medium: '400' as const,
    semibold: '400' as const,
    bold: '400' as const,
  },
}
