import { StyleSheet } from 'react-native'
import { AppTheme } from '@/src/shared/theme/colors'
import { typography } from '@/src/shared/theme/typography'

export function createStyles({ colors, shadows }: AppTheme) {
  return StyleSheet.create({
    content: {
      paddingHorizontal: 0,
      paddingTop: 0,
    },
    inner: {
      flex: 1,
      padding: 18,
    },
    titleRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 18,
      marginTop: 22,
    },
    title: {
      color: colors.text,
      fontFamily: typography.familyBold,
      fontSize: typography.size.screenTitle,
      fontWeight: typography.weight.bold,
    },
    subtitle: {
      color: colors.textMuted,
      fontFamily: typography.familyBold,
      fontSize: typography.size.label,
      fontWeight: typography.weight.medium,
      marginTop: 4,
    },
    refreshButton: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.surfaceVariant,
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    filterRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 10,
    },
    filterChip: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.surfaceVariant,
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      minHeight: 48,
      paddingHorizontal: 14,
      justifyContent: 'center',
    },
    filterChipSmall: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.surfaceVariant,
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      minHeight: 48,
      paddingHorizontal: 12,
      justifyContent: 'center',
    },
    filterChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    filterText: {
      color: colors.textMuted,
      fontFamily: typography.familyBold,
      fontSize: typography.size.label,
      fontWeight: typography.weight.semibold,
    },
    filterTextActive: {
      color: colors.white,
    },
    stateBlock: {
      alignItems: 'center',
      gap: 10,
      paddingVertical: 22,
    },
    stateText: {
      color: colors.textMuted,
      fontFamily: typography.familyBold,
      fontSize: typography.size.bodySmall,
      fontWeight: typography.weight.medium,
    },
    bulkReviewRow: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.surfaceVariant,
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
      marginBottom: 12,
      padding: 14,
    },
    bulkReviewTextBlock: {
      flex: 1,
      gap: 3,
    },
    bulkReviewTitle: {
      color: colors.text,
      fontFamily: typography.familyBold,
      fontSize: typography.size.bodySmall,
      fontWeight: typography.weight.semibold,
    },
    bulkReviewText: {
      color: colors.textMuted,
      fontFamily: typography.familyBold,
      fontSize: typography.size.caption,
      fontWeight: typography.weight.medium,
    },
    confirmAllButton: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 8,
      flexDirection: 'row',
      gap: 6,
      justifyContent: 'center',
      minHeight: 48,
      minWidth: 128,
      paddingHorizontal: 14,
    },
    confirmAllButtonText: {
      color: colors.white,
      fontFamily: typography.familyBold,
      fontSize: typography.size.label,
      fontWeight: typography.weight.semibold,
    },
    errorBlock: {
      backgroundColor: colors.dangerSoft,
      borderRadius: 10,
      marginBottom: 12,
      padding: 14,
    },
    errorText: {
      color: colors.danger,
      fontFamily: typography.familyBold,
      fontSize: typography.size.label,
      fontWeight: typography.weight.semibold,
      textAlign: 'center',
    },
    list: {
      gap: 12,
      paddingBottom: 100,
    },
    item: {
      gap: 12,
      padding: 14,
    },
    itemHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
    },
    iconCircle: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 24,
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    itemText: {
      flex: 1,
    },
    itemTitle: {
      color: colors.text,
      fontFamily: typography.familyBold,
      fontSize: typography.size.titleSmall,
      fontWeight: typography.weight.semibold,
    },
    status: {
      color: colors.textMuted,
      fontFamily: typography.family,
      fontSize: typography.size.bodySmall,
      marginTop: 4,
    },
    amount: {
      color: colors.success,
      fontFamily: typography.familyBold,
      fontSize: typography.size.bodyLarge,
      fontWeight: typography.weight.bold,
    },
    metaRow: {
      backgroundColor: colors.surfaceMuted,
      borderRadius: 8,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    metaText: {
      color: colors.textMuted,
      fontFamily: typography.familyBold,
      fontSize: typography.size.caption,
      fontWeight: typography.weight.semibold,
    },
    noteText: {
      color: colors.textMuted,
      fontFamily: typography.family,
      fontSize: typography.size.bodySmall,
      lineHeight: typography.lineHeight.bodySmall,
    },
    reviewActions: {
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'flex-end',
    },
    reviewButton: {
      alignItems: 'center',
      borderRadius: 8,
      flexDirection: 'row',
      gap: 6,
      justifyContent: 'center',
      minHeight: 48,
      minWidth: 96,
      paddingHorizontal: 12,
    },
    confirmButton: {
      backgroundColor: colors.primary,
    },
    rejectButton: {
      backgroundColor: colors.surface,
      borderColor: colors.danger,
      borderWidth: StyleSheet.hairlineWidth,
    },
    actionPressed: {
      opacity: 0.65,
    },
    reviewButtonText: {
      fontFamily: typography.familyBold,
      fontSize: typography.size.label,
      fontWeight: typography.weight.semibold,
    },
    confirmButtonText: {
      color: colors.white,
    },
    rejectButtonText: {
      color: colors.danger,
    },
    emptyCard: {
      alignItems: 'center',
      gap: 8,
      paddingVertical: 28,
    },
    emptyTitle: {
      color: colors.text,
      fontFamily: typography.familyBold,
      fontSize: typography.size.bodyLarge,
      fontWeight: typography.weight.bold,
    },
    emptyText: {
      color: colors.textMuted,
      fontFamily: typography.family,
      fontSize: typography.size.bodySmall,
      lineHeight: typography.lineHeight.bodySmall,
      textAlign: 'center',
    },
    loadMoreButton: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.surfaceVariant,
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      justifyContent: 'center',
      marginTop: 4,
      minHeight: 48,
      minWidth: 132,
      paddingHorizontal: 16,
    },
    loadMoreText: {
      color: colors.primary,
      fontFamily: typography.familyBold,
      fontSize: typography.size.label,
      fontWeight: typography.weight.semibold,
    },
  })
}
