import { StyleSheet } from 'react-native'
import { colors, shadows } from '@/src/shared/theme/colors'

export const styles = StyleSheet.create({
  content: {
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  keyboardRoot: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 28,
  },
  header: {
    alignItems: 'center',
    borderBottomColor: colors.surfaceVariant,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    height: 72,
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  backButton: {
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  headerTitle: {
    color: colors.text,
    fontSize: 27,
    fontWeight: '800',
  },
  amountSection: {
    alignItems: 'center',
    gap: 10,
    paddingBottom: 30,
    paddingTop: 34,
  },
  amountLabel: {
    color: colors.textMuted,
    fontSize: 18,
    fontWeight: '600',
  },
  amountRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 22,
  },
  currency: {
    color: colors.text,
    fontSize: 68,
    fontWeight: '800',
    opacity: 0.48,
  },
  amountInput: {
    color: colors.text,
    fontSize: 68,
    fontWeight: '800',
    minWidth: 190,
    paddingVertical: 0,
  },
  formCard: {
    gap: 22,
    marginHorizontal: 18,
    padding: 20,
  },
  floatingField: {
    paddingTop: 6,
  },
  floatingLabel: {
    backgroundColor: colors.surface,
    color: colors.textMuted,
    fontSize: 17,
    fontWeight: '600',
    left: 18,
    paddingHorizontal: 6,
    position: 'absolute',
    top: -4,
    zIndex: 1,
  },
  outlinedInput: {
    alignItems: 'center',
    borderColor: colors.outlineStrong,
    borderRadius: 12,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 16,
    height: 64,
    paddingHorizontal: 18,
  },
  titleInput: {
    color: colors.text,
    flex: 1,
    fontSize: 19,
  },
  fieldBlock: {
    gap: 10,
  },
  inputLabel: {
    color: colors.textMuted,
    fontSize: 16,
    fontWeight: '700',
  },
  groupList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  groupPill: {
    borderColor: colors.outline,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  groupPillActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  groupPillText: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '700',
  },
  groupPillTextActive: {
    color: colors.primary,
  },
  selectBox: {
    alignItems: 'center',
    borderColor: colors.outline,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    height: 68,
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  payerLeft: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  meAvatar: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  meText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  payerName: {
    color: colors.text,
    flexShrink: 1,
    fontSize: 22,
    fontWeight: '700',
  },
  splitCard: {
    gap: 24,
    marginHorizontal: 18,
    marginTop: 30,
    padding: 20,
  },
  splitHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerIconButton: {
    alignItems: 'center',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  splitTitle: {
    color: colors.text,
    fontSize: 29,
    fontWeight: '800',
  },
  segmented: {
    backgroundColor: colors.surfaceVariant,
    borderRadius: 30,
    flexDirection: 'row',
    padding: 5,
  },
  segmentActive: {
    alignItems: 'center',
    backgroundColor: colors.successSoft,
    borderRadius: 25,
    flex: 1,
    height: 50,
    justifyContent: 'center',
  },
  segmentInactive: {
    alignItems: 'center',
    borderRadius: 25,
    flex: 1,
    height: 50,
    justifyContent: 'center',
  },
  segmentActiveText: {
    color: colors.success,
    fontSize: 17,
    fontWeight: '800',
  },
  segmentInactiveText: {
    color: colors.textMuted,
    fontSize: 17,
    fontWeight: '700',
  },
  participants: {
    gap: 16,
  },
  participantRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  participantLeft: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
    flex: 1,
    paddingRight: 10,
  },
  participantText: {
    flex: 1,
  },
  participantAvatar: {
    alignItems: 'center',
    borderRadius: 24,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  participantInitials: {
    fontSize: 17,
    fontWeight: '800',
  },
  participantName: {
    color: colors.text,
    fontSize: 21,
    fontWeight: '700',
  },
  participantNote: {
    color: colors.textSoft,
    fontSize: 15,
    fontWeight: '600',
  },
  checkbox: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 7,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  checkboxInactive: {
    backgroundColor: colors.surface,
    borderColor: colors.outline,
    borderWidth: 1.5,
  },
  shareInput: {
    borderColor: colors.outline,
    borderRadius: 12,
    borderWidth: 1,
    color: colors.text,
    fontSize: 17,
    fontWeight: '700',
    height: 46,
    paddingHorizontal: 12,
    textAlign: 'right',
    width: 104,
  },
  splitSummary: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  summaryText: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '700',
  },
  loadingMembers: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  helperText: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 21,
  },
  errorBlock: {
    backgroundColor: colors.dangerSoft,
    borderRadius: 12,
    marginHorizontal: 18,
    marginTop: 18,
    padding: 14,
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    textAlign: 'center',
  },
  bottomAction: {
    backgroundColor: colors.surface,
    borderTopColor: colors.surfaceVariant,
    borderTopWidth: StyleSheet.hairlineWidth,
    padding: 18,
  },
  createButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 32,
    flexDirection: 'row',
    gap: 12,
    height: 64,
    justifyContent: 'center',
    ...shadows.floating,
  },
  createButtonDisabled: {
    backgroundColor: colors.outline,
    shadowOpacity: 0,
    elevation: 0,
  },
  createText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '700',
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.32)',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  modalCard: {
    maxHeight: '78%',
    padding: 18,
    width: '100%',
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  modalTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
  },
  closeButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  memberList: {
    gap: 12,
    paddingBottom: 16,
  },
  memberPickerRow: {
    alignItems: 'center',
    borderColor: colors.surfaceVariant,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 12,
  },
  doneButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 24,
    height: 52,
    justifyContent: 'center',
  },
  doneText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },
})
